#!/bin/bash

source $(dirname "$0")/functions.sh

now=`date +%s`
echo ${now}:checkout >> ${timeIssueFile}

issue=$(getIssue)

assignedToUserID=`echo $issue | jq -r ".issue.assigned_to.id"`
if [ ${assignedToUserID} == "null" ]; then
  cat << EOF > ${redmineIssueFile}
{
  "issue": {
    "status_id": "${REDMINE_IN_PROGRESS_STATUS_ID}",
    "assigned_to_id": "${userID}"
  }
}
EOF
  
  updateIssue
fi

rm ${redmineIssueFile}
